all: search1 search2

search1: search1.cpp
	g++ -std=c++11 -o search1 search1.cpp -I/usr/local/include/libxml2 -L/usr/local/lib -lxml2

search2: search2.cpp
	g++ -std=c++11 -o search2 search2.cpp -I/usr/local/include/libxml2 -L/usr/local/lib -lxml2 